<a href="https://colab.research.google.com/github/FrankGangWang/AppliedML_Python_Coursera/blob/master/Exeter_Test_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
def func_sum_counts(ct):
  sum = 0
  for key in ct.keys():
    sum += ct.get(key)
  return sum

def func_count_chars(line, counter):
  """func to count number of strings in string 'line' based on current 'counter'.
  Note: set counter = {} for the first line;
  """
  for c in line:
    counter[c] = counter.get(c, 0) + 1
  return counter

f = open("test.txt", "r")
ct = {}

count_chars = 0
for number_of_lines, line in enumerate(f):
  if number_of_lines<5:
    print(f'***num of chars in line {c} is {len(line), {line[-5:]}}')
  line = line.rstrip('\n')
  count_chars += len(line)
  ct = func_count_chars(line, ct)

  if number_of_lines==1:
    print(line[100:110])

  if number_of_lines<5:
    print(f'num of chars in line {number_of_lines} is {len(line), {line[-5:]}}')
    print('  accumulated num of chars=', count_chars)
    print('  count per string=', ct)

f.close()
number_of_lines = number_of_lines + 1

***num of chars in line E is (106, {'DEGE\n'})
num of chars in line 0 is (105, {'GDEGE'})
  accumulated num of chars= 105
  count per string= {'E': 32, 'D': 10, 'G': 31, 'C': 17, 'F': 15}
***num of chars in line E is (114, {'CEGE\n'})
GGGDEGECGC
num of chars in line 1 is (113, {'GCEGE'})
  accumulated num of chars= 218
  count per string= {'E': 69, 'D': 20, 'G': 64, 'C': 35, 'F': 30}
***num of chars in line E is (114, {'CEGC\n'})
num of chars in line 2 is (113, {'GCEGC'})
  accumulated num of chars= 331
  count per string= {'E': 107, 'D': 30, 'G': 97, 'C': 52, 'F': 45}
***num of chars in line E is (113, {'CGCE\n'})
num of chars in line 3 is (112, {'ECGCE'})
  accumulated num of chars= 443
  count per string= {'E': 145, 'D': 40, 'G': 129, 'C': 69, 'F': 60}
***num of chars in line E is (116, {'EGEE\n'})
num of chars in line 4 is (115, {'CEGEE'})
  accumulated num of chars= 558
  count per string= {'E': 184, 'D': 50, 'G': 162, 'C': 86, 'F': 76}


In [11]:
print('number of lines=', number_of_lines)
print('number of chars \t=', count_chars)
print('sum counts per char\t=', func_sum_counts(ct))
print('counts per char=', ct)

number of lines= 300
number of chars 	= 32363
sum counts per char	= 32363
counts per char= {'E': 10615, 'D': 2854, 'G': 9351, 'C': 5081, 'F': 4462}


In [26]:
chars = sorted(ct.keys())
df = np.zeros((number_of_lines, len(chars)))
df[0]

array([0., 0., 0., 0., 0.])

In [54]:
def func_count_chars_ordered(line, chars):
  """func to count number of strings in string 'line' based on current 'counter'.
  Note: set counter = {} for the first line;
  """
  counter = np.zeros((len(chars, )))
  #print(counter, line, chars)
  for id, c in enumerate(chars):
    #print(f'id={id}, ch={chars[id]}')
    counter[id] = line.count(chars[id])
  return counter

func_count_chars_ordered('CCDCDEFGA', chars)

array([3., 2., 1., 1., 1.])

In [55]:
func_count_chars_ordered(line, chars)


array([17., 10., 38., 15., 34.])

In [56]:
import numpy as np
import pandas as pd

chars = sorted(ct.keys())
df = np.zeros((number_of_lines, len(chars)))
print(chars, df.shape)

f = open("test.txt", "r")
for c, line in enumerate(f):
  if c<5:
    print(f'***num of chars in line {c} is {len(line), {line[-5:]}}')
  line = line.rstrip('\n')
  df[c] = func_count_chars_ordered(line, chars)
f.close()

df = pd.DataFrame(df, columns=chars)


['C', 'D', 'E', 'F', 'G'] (300, 5)
***num of chars in line 0 is (106, {'DEGE\n'})
***num of chars in line 1 is (114, {'CEGE\n'})
***num of chars in line 2 is (114, {'CEGC\n'})
***num of chars in line 3 is (113, {'CGCE\n'})
***num of chars in line 4 is (116, {'EGEE\n'})


In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   C       300 non-null    float64
 1   D       300 non-null    float64
 2   E       300 non-null    float64
 3   F       300 non-null    float64
 4   G       300 non-null    float64
dtypes: float64(5)
memory usage: 11.8 KB


In [59]:
df['C']

0      17.0
1      18.0
2      17.0
3      17.0
4      17.0
       ... 
295    15.0
296    17.0
297    17.0
298    18.0
299    17.0
Name: C, Length: 300, dtype: float64

In [75]:
from numpy import mean
from numpy import std

# calculate summary statistics
data_mean, data_std = mean(df), std(df)
# identify outliers
cut_off = data_std * 2
lower, upper = data_mean - cut_off, data_mean + cut_off
# identify outliers
for ch in chars:
  outliers = [x for x in df[ch] if x < lower[ch] or x > upper[ch]]
  outliers_idx = df.index[df[ch]==outliers[0]].tolist()

  print(ch, outliers, '\n', outliers_idx)

C [14.0, 14.0, 14.0, 14.0, 14.0, 14.0] 
 [50, 77, 161, 170, 265, 269]
D [8.0, 7.0, 8.0, 8.0, 8.0, 8.0, 8.0, 6.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 7.0] 
 [24, 63, 100, 104, 122, 133, 151, 154, 159, 161, 164, 169, 187, 202, 228, 252]
E [40.0, 31.0, 40.0, 30.0, 40.0, 40.0, 30.0, 40.0, 40.0, 40.0] 
 [11, 25, 135, 141, 166, 283, 287]
F [13.0, 13.0, 13.0, 11.0, 13.0, 12.0, 13.0, 13.0, 13.0, 13.0, 12.0, 13.0] 
 [13, 54, 56, 147, 152, 154, 155, 163, 176]
G [27.0, 26.0, 25.0, 27.0] 
 [94, 269]


/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


In [72]:
#df['C']==14.0
df.index[df['C']==14.0].tolist()


[50, 77, 161, 170, 265, 269]

In [ ]:
data_mean, data_std

In [ ]:
lower, upper

In [ ]:
df['C']

In [76]:
df.describe()

C           D           E           F          G
count  300.000000  300.000000  300.000000  300.000000  300.00000
mean    16.936667    9.513333   35.383333   14.873333   31.17000
std      1.062899    0.661777    2.068167    0.725057    1.59465
min     14.000000    6.000000   30.000000   11.000000   25.00000
25%     16.000000    9.000000   34.000000   15.000000   30.00000
50%     17.000000   10.000000   35.000000   15.000000   31.00000
75%     18.000000   10.000000   37.000000   15.000000   32.00000
max     18.000000   10.000000   40.000000   16.000000   34.00000

In [78]:
import plotly.express as px
#create a histogram

fig = px.histogram(df, x='C')

fig.show()

In [80]:
#create a box plot

fig = px.box(df, y='C')

fig.show()

In [82]:
chars

['C', 'D', 'E', 'F', 'G']

In [81]:
fig = px.scatter(x=df['C'], y=df['D'])

fig.show()

In [85]:
import numpy as np
from sklearn.neighbors import LocalOutlierFactor
X = [[-1.1], [0.2], [101.1], [0.3]]
clf = LocalOutlierFactor(n_neighbors=2)
print(clf.fit_predict(X))

print(clf.negative_outlier_factor_)


[ 1  1 -1  1]
[ -0.98214286  -1.03703704 -73.36970899  -0.98214286]


In [103]:
n_neighbors = 50
clf = LocalOutlierFactor(n_neighbors=n_neighbors)
results = clf.fit_predict(df)
print(np.where(results==-1))

(array([ 45, 137, 140, 143, 146, 148, 155, 164, 262, 288]),)


In [105]:
n_neighbors = 100
clf = LocalOutlierFactor(n_neighbors=n_neighbors)
results = clf.fit_predict(df)
print(np.where(results==-1))

(array([140, 262]),)


In [104]:
n_neighbors = 150
clf = LocalOutlierFactor(n_neighbors=n_neighbors)
results = clf.fit_predict(df)
print(np.where(results==-1))

(array([262]),)


In [102]:
df.iloc[np.where(results==-1)].T

45    135   137   140   143   146   148   155   164   190   262   288
C  18.0  16.0  16.0  16.0  18.0  17.0  18.0  15.0  17.0  16.0  15.0  18.0
D  10.0   9.0  10.0   6.0   9.0   9.0  10.0  10.0   8.0   9.0   9.0   7.0
E  39.0  40.0  34.0  32.0  30.0  38.0  34.0  39.0  38.0  34.0  36.0  38.0
F  15.0  16.0  11.0  15.0  15.0  15.0  12.0  13.0  12.0  15.0  15.0  15.0
G  29.0  34.0  31.0  33.0  30.0  28.0  29.0  31.0  31.0  26.0  25.0  31.0

In [108]:
n_neighbors = 50
clf = LocalOutlierFactor(n_neighbors=n_neighbors)
results = clf.fit_predict(df)
print(np.where(results==-1))
print(df.iloc[np.where(results==-1)].T)


(array([ 45, 137, 140, 143, 146, 148, 155, 164, 262, 288]),)
    45    137   140   143   146   148   155   164   262   288
C  18.0  16.0  16.0  18.0  17.0  18.0  15.0  17.0  15.0  18.0
D  10.0  10.0   6.0   9.0   9.0  10.0  10.0   8.0   9.0   7.0
E  39.0  34.0  32.0  30.0  38.0  34.0  39.0  38.0  36.0  38.0
F  15.0  11.0  15.0  15.0  15.0  12.0  13.0  12.0  15.0  15.0
G  29.0  31.0  33.0  30.0  28.0  29.0  31.0  31.0  25.0  31.0


In [107]:
df.iloc[np.where(results==-1)]

C    D     E     F     G
140  16.0  6.0  32.0  15.0  33.0
262  15.0  9.0  36.0  15.0  25.0

In [101]:
df.describe()

C           D           E           F          G
count  300.000000  300.000000  300.000000  300.000000  300.00000
mean    16.936667    9.513333   35.383333   14.873333   31.17000
std      1.062899    0.661777    2.068167    0.725057    1.59465
min     14.000000    6.000000   30.000000   11.000000   25.00000
25%     16.000000    9.000000   34.000000   15.000000   30.00000
50%     17.000000   10.000000   35.000000   15.000000   31.00000
75%     18.000000   10.000000   37.000000   15.000000   32.00000
max     18.000000   10.000000   40.000000   16.000000   34.00000

In [88]:
print(clf.negative_outlier_factor_)

[-1.10355339e+00 -1.00000000e+00 -5.00000000e+09 -1.00000000e+00
 -9.14213562e-01 -1.10355339e+00 -1.00000000e+00 -1.29289322e+00
 -1.00000000e+00 -5.00000000e+09 -1.00000000e+00 -1.00000000e+00
 -9.14213562e-01 -1.20710678e+00 -1.00000000e+00 -1.10355339e+00
 -1.10355339e+00 -1.00000000e+00 -1.00000000e+10 -9.49489743e-01
 -1.41421356e+00 -1.73205081e+10 -1.00000000e+00 -1.00000000e+00
 -1.41421356e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
 -1.00000000e+00 -1.00000000e+00 -1.20779890e+00 -1.00000000e+00
 -5.00000000e+09 -1.00000000e+00 -1.00000000e+00 -1.29289322e+00
 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00
 -1.00000000e+00 -5.00000000e+09 -1.00000000e+00 -1.10355339e+00
 -1.10355339e+00 -1.37731840e+00 -9.14213562e-01 -1.00000000e+00
 -1.00000000e+00 -1.00000000e+00 -1.57313218e+00 -9.14213562e-01
 -5.00000000e+09 -1.58346434e+00 -1.29289322e+00 -1.00000000e+00
 -1.30322537e+00 -1.10355339e+00 -1.00000000e+00 -1.00000000e+00
 -1.57313218e+00 -1.00000